postgres:
  image: postgres

activemq:
  image: webcenter/activemq

cassandra:
  image: cassandra
  ports:
    - "9160:9160"
    - "9042:9042"

assistanceplatform:
  image: assistance-platform-service
  command: '-Dconfig.resource=docker.conf'
  ports:
      - "9000:9000"
  links:
      - postgres:db
      - cassandra
      - activemq

spark-master:
  image: gettyimages/spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  hostname: spark-master
  environment:
    SPARK_CONF_DIR: /conf
    MASTER: spark://spark-master:7077
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data
