---
# ActiveMQ config
ACTIVEMQ_VERSION: "5.14.0"
ACTIVEMQ_USER: "activemq"
ACTIVEMQ_INSTALLATION_DIR: "/usr/share/activemq"
ACTIVEMQ_PORT_61616_TCP_ADDR: "127.0.0.1"
ACTIVEMQ_PORT_61616_TCP_PORT: "61616"