---
- name: Postgres | Install with dependencies
  apt: 
    name={{ item }} 
    state=present 
    update_cache=yes
  with_items:
    [postgresql, postgresql-contrib, libpq-dev, python-psycopg2]
  tags:
    [install, postgres]

- name: Postgres | Add user
  user: 
    name={{ POSTGRES_SYSTEM_USER }}
  tags:
    [install, postgres]
  
- name: Postgres | Create database
  postgresql_db: 
    name={{ POSTGRES_DB_NAME }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    state=present
  become_user: "{{ POSTGRES_SYSTEM_USER }}"
  tags:
    [install, postgres]

- name: Postgres | Create user (role)
  postgresql_user: 
    db={{ POSTGRES_DB_NAME }}
    name={{ POSTGRES_DB_USER }}
    password={{ POSTGRES_DB_PASS }}
    priv=ALL
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present
  become_user: "{{ POSTGRES_SYSTEM_USER }}"
  tags:
    [install, postgres]