---
- name: Install Cassandra source
  lineinfile: dest=/etc/apt/sources.list.d/cassandra.sources.list state=present insertafter=EOF create=yes line="deb http://debian.datastax.com/community stable main"

- name: Add Cassandra repo key
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present

- name: Install Cassandra
  apt: name=cassandra state=present update_cache=yes