---
- name: SBT clean project
  shell: sbt clean
  args:
    chdir: "{{ PROJECT_ROOT }}/assistance-platform-service/"
  tags:
    [install, assistance]

- name: Create and publish docker image to local repository
  shell: sbt docker
  args:
    chdir: "{{ PROJECT_ROOT }}/assistance-platform-service/"
  tags:
    [install, assistance]

- name: Run generated docker container
  docker_container:
    name: assistance
    hostname: assi
    image: telecooperation/assistance-platform-service
    state: started
    restart_retries: 5
    restart: no
    command: "-Dconfig.resource=docker.conf"
    published_ports:
      - "9000"
    links:
      - postgres
      - cassandra
      - activemq
    env:
      VIRTUAL_HOST: assi
      VIRTUAL_PORT: 9000
      ACTIVEMQ_PORT_61616_TCP_ADDR: "{{ ACTIVEMQ_PORT_61616_TCP_ADDR }}"
      ACTIVEMQ_PORT_61616_TCP_PORT: "{{ ACTIVEMQ_PORT_61616_TCP_PORT }}"
      DB_PORT_5432_TCP_ADDR: "{{ DB_PORT_5432_TCP_ADDR }}"
      DB_PORT_5432_TCP_PORT: "{{ DB_PORT_5432_TCP_PORT }}"
      CASSANDRA_PORT_9042_TCP_ADDR: "{{ CASSANDRA_PORT_9042_TCP_ADDR }}"
      CASSANDRA_PORT_9042_TCP_PORT: "{{ CASSANDRA_PORT_9042_TCP_PORT }}"
  tags:
    [run, assistance]