---
- name: Copy docker config
  template:
    src=docker.conf
    dest={{ PROJECT_ROOT }}/assistance-platform-service/conf/docker.conf
    mode=0655
  tags:
    [install, assistance]

- name: Copy application config
  template:
    src=application.conf
    dest={{ PROJECT_ROOT }}/assistance-platform-service/conf/application.conf
    mode=0655
  tags:
    [install, assistance]

- block:
    - include: run.yml
  rescue:
    - name: SBT clean project
      shell: "sbt clean"
      args:
        chdir: "{{ PROJECT_ROOT }}/assistance-platform-service/"
      tags:
        [install, assistance]

    - name: Create and publish docker image to local repository
      shell: "sbt docker"
      args:
        chdir: "{{ PROJECT_ROOT }}/assistance-platform-service/"
      tags:
        [install, assistance]

    - include: run.yml