---
# Postgres config
POSTGRES_SYSTEM_USER: "assistance-postgres"
POSTGRES_DB_NAME: "assistance-postgres"
POSTGRES_DB_USER: "assistance-postgres"
POSTGRES_DB_PASS: "assistancepass"
DB_PORT_5432_TCP_ADDR: "127.0.0.1"
DB_PORT_5432_TCP_PORT: "5432"