---
- name: Cassandra | Install source entry
  apt_repository:
    repo="deb http://debian.datastax.com/community stable main"
    state=present
    filename="cassandra.sources"
  tags:
    [install, cassandra]

- name: Cassandra | Add repo key
  apt_key: 
    url=http://debian.datastax.com/debian/repo_key 
    state=present
  tags:
    [install, cassandra]

- name: Cassandra | Install
  apt: 
    name=cassandra 
    state=present 
    update_cache=yes
  tags:
    [install, cassandra]

- name: Cassandra | Copy config file
  copy: 
    src={{ PROJECT_ROOT }}/deployment/ansible/files/cassandra/cassandra.yaml 
    dest=/etc/cassandra/cassandra.yaml
  notify:
    - Postgres | Restart service
  tags:
    [install, cassandra]

- name: Cassandra | Start/Restart service
  service: 
    name=cassandra 
    state=restarted
  tags: 
    [run, cassandra]