---
- name: Pull/run docker container
  docker_container:
    name: activemq
    image: webcenter/activemq
    hostname: activemq
    tls: yes
    state: started
    restart_retries: 5
    restart: no
    published_ports:
      - "{{ ACTIVEMQ_PORT_61616_TCP_PORT }}:{{ ACTIVEMQ_PORT_61616_TCP_PORT }}"
      - "{{ ACTIVEMQ_PORT_8161_TCP_PORT }}:{{ ACTIVEMQ_PORT_8161_TCP_PORT }}"
  tags:
    [run, activemq]