---
- name: Pull/run docker container
  docker_container:
    name: postgres
    hostname: "{{ DB_PORT_5432_TCP_ADDR }}"
    image: postgres
    tls: yes
    state: started
    restart_retries: 5
    restart: no
    published_ports:
      - "{{ DB_PORT_5432_TCP_PORT }}:{{ DB_PORT_5432_TCP_PORT }}"
  tags:
    [run, postgres]